//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/28/2016 11:54:39 AM
namespace ExampleODataFromDocumentDb.Client
{
    /// <summary>
    /// There are no comments for ExampleODataFromDocumentDbClient in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ExampleODataFromDocumentDbClient")]
    public partial class ExampleODataFromDocumentDbClient : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ExampleODataFromDocumentDbClient object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public ExampleODataFromDocumentDbClient(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ExampleODataFromDocumentDb", "ExampleODataFromDocumentDb.Client");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("ExampleODataFromDocumentDb.Client", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("ExampleODataFromDocumentDb.", originalNameAttribute.OriginalName);
                }
                return string.Concat("ExampleODataFromDocumentDb.", clientType.Name);
            }
            if (originalNameAttribute != null)
            {
                return clientType.Namespace + "." + originalNameAttribute.OriginalName;
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Houses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Houses")]
        public global::Microsoft.OData.Client.DataServiceQuery<House> Houses
        {
            get
            {
                if ((this._Houses == null))
                {
                    this._Houses = base.CreateQuery<House>("Houses");
                }
                return this._Houses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<House> _Houses;
        /// <summary>
        /// There are no comments for HouseHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HouseHistory")]
        public global::Microsoft.OData.Client.DataServiceQuery<HouseHistory> HouseHistory
        {
            get
            {
                if ((this._HouseHistory == null))
                {
                    this._HouseHistory = base.CreateQuery<HouseHistory>("HouseHistory");
                }
                return this._HouseHistory;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<HouseHistory> _HouseHistory;
        /// <summary>
        /// There are no comments for Houses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToHouses(House house)
        {
            base.AddObject("Houses", house);
        }
        /// <summary>
        /// There are no comments for HouseHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToHouseHistory(HouseHistory houseHistory)
        {
            base.AddObject("HouseHistory", houseHistory);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""ExampleODataFromDocumentDb"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""House"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""ETag"" Type=""Edm.String"" ConcurrencyMode=""Fixed"" />
        <Property Name=""DocumentType"" Type=""ExampleODataFromDocumentDb.DocumentType"" />
        <Property Name=""CreateDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""UpdateDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""TestName"" Type=""Edm.String"" />
        <Property Name=""TestDateTimeOffset"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""TestDateTimeOffsetNullable"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""TestSkylight"" Type=""ExampleODataFromDocumentDb.Window"" />
        <Property Name=""TestWindows"" Type=""Collection(ExampleODataFromDocumentDb.Window)"" />
      </EntityType>
      <EntityType Name=""HouseHistory"" BaseType=""ExampleODataFromDocumentDb.House"">
        <Property Name=""ModifiedId"" Type=""Edm.String"" />
        <Property Name=""ModifyAction"" Type=""Edm.String"" />
        <Property Name=""ModifyTimestamp"" Type=""Edm.DateTimeOffset"" />
      </EntityType>
      <ComplexType Name=""Window"">
        <Property Name=""WidthInches"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""HeightInches"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Panes"" Type=""Collection(ExampleODataFromDocumentDb.GlassPane)"" />
        <Property Name=""InstalledDate"" Type=""Edm.DateTimeOffset"" />
      </ComplexType>
      <ComplexType Name=""GlassPane"">
        <Property Name=""WidthInches"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""HeightInches"" Type=""Edm.Int32"" Nullable=""false"" />
      </ComplexType>
      <EnumType Name=""DocumentType"">
        <Member Name=""Invalid"" Value=""0"" />
        <Member Name=""House"" Value=""1"" />
        <Member Name=""HouseHistory"" Value=""2"" />
        <Member Name=""Car"" Value=""3"" />
        <Member Name=""CarHistory"" Value=""4"" />
      </EnumType>
      <EntityContainer Name=""ExampleODataFromDocumentDbClient"">
        <EntitySet Name=""Houses"" EntityType=""ExampleODataFromDocumentDb.House"">
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>ETag</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
        <EntitySet Name=""HouseHistory"" EntityType=""ExampleODataFromDocumentDb.HouseHistory"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for HouseSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("HouseSingle")]
    public partial class HouseSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<House>
    {
        /// <summary>
        /// Initialize a new HouseSingle object.
        /// </summary>
        public HouseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new HouseSingle object.
        /// </summary>
        public HouseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new HouseSingle object.
        /// </summary>
        public HouseSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<House> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for House in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.EntitySet("Houses")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("House")]
    public partial class House : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new House object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static House CreateHouse(string ID)
        {
            House house = new House();
            house.Id = ID;
            return house;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ETag in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ETag")]
        public string ETag
        {
            get
            {
                return this._ETag;
            }
            set
            {
                this.OnETagChanging(value);
                this._ETag = value;
                this.OnETagChanged();
                this.OnPropertyChanged("ETag");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ETag;
        partial void OnETagChanging(string value);
        partial void OnETagChanged();
        /// <summary>
        /// There are no comments for Property DocumentType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DocumentType")]
        public global::System.Nullable<global::ExampleODataFromDocumentDb.Client.DocumentType> DocumentType
        {
            get
            {
                return this._DocumentType;
            }
            set
            {
                this.OnDocumentTypeChanging(value);
                this._DocumentType = value;
                this.OnDocumentTypeChanged();
                this.OnPropertyChanged("DocumentType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::ExampleODataFromDocumentDb.Client.DocumentType> _DocumentType;
        partial void OnDocumentTypeChanging(global::System.Nullable<global::ExampleODataFromDocumentDb.Client.DocumentType> value);
        partial void OnDocumentTypeChanged();
        /// <summary>
        /// There are no comments for Property CreateDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreateDate")]
        public global::System.Nullable<global::System.DateTimeOffset> CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this._CreateDate = value;
                this.OnCreateDateChanged();
                this.OnPropertyChanged("CreateDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreateDate;
        partial void OnCreateDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// There are no comments for Property UpdateDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UpdateDate")]
        public global::System.Nullable<global::System.DateTimeOffset> UpdateDate
        {
            get
            {
                return this._UpdateDate;
            }
            set
            {
                this.OnUpdateDateChanging(value);
                this._UpdateDate = value;
                this.OnUpdateDateChanged();
                this.OnPropertyChanged("UpdateDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _UpdateDate;
        partial void OnUpdateDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnUpdateDateChanged();
        /// <summary>
        /// There are no comments for Property TestName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TestName")]
        public string TestName
        {
            get
            {
                return this._TestName;
            }
            set
            {
                this.OnTestNameChanging(value);
                this._TestName = value;
                this.OnTestNameChanged();
                this.OnPropertyChanged("TestName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _TestName;
        partial void OnTestNameChanging(string value);
        partial void OnTestNameChanged();
        /// <summary>
        /// There are no comments for Property TestDateTimeOffset in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TestDateTimeOffset")]
        public global::System.Nullable<global::System.DateTimeOffset> TestDateTimeOffset
        {
            get
            {
                return this._TestDateTimeOffset;
            }
            set
            {
                this.OnTestDateTimeOffsetChanging(value);
                this._TestDateTimeOffset = value;
                this.OnTestDateTimeOffsetChanged();
                this.OnPropertyChanged("TestDateTimeOffset");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _TestDateTimeOffset;
        partial void OnTestDateTimeOffsetChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnTestDateTimeOffsetChanged();
        /// <summary>
        /// There are no comments for Property TestDateTimeOffsetNullable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TestDateTimeOffsetNullable")]
        public global::System.Nullable<global::System.DateTimeOffset> TestDateTimeOffsetNullable
        {
            get
            {
                return this._TestDateTimeOffsetNullable;
            }
            set
            {
                this.OnTestDateTimeOffsetNullableChanging(value);
                this._TestDateTimeOffsetNullable = value;
                this.OnTestDateTimeOffsetNullableChanged();
                this.OnPropertyChanged("TestDateTimeOffsetNullable");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _TestDateTimeOffsetNullable;
        partial void OnTestDateTimeOffsetNullableChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnTestDateTimeOffsetNullableChanged();
        /// <summary>
        /// There are no comments for Property TestSkylight in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TestSkylight")]
        public global::ExampleODataFromDocumentDb.Client.Window TestSkylight
        {
            get
            {
                return this._TestSkylight;
            }
            set
            {
                this.OnTestSkylightChanging(value);
                this._TestSkylight = value;
                this.OnTestSkylightChanged();
                this.OnPropertyChanged("TestSkylight");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ExampleODataFromDocumentDb.Client.Window _TestSkylight;
        partial void OnTestSkylightChanging(global::ExampleODataFromDocumentDb.Client.Window value);
        partial void OnTestSkylightChanged();
        /// <summary>
        /// There are no comments for Property TestWindows in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TestWindows")]
        public global::System.Collections.ObjectModel.ObservableCollection<global::ExampleODataFromDocumentDb.Client.Window> TestWindows
        {
            get
            {
                return this._TestWindows;
            }
            set
            {
                this.OnTestWindowsChanging(value);
                this._TestWindows = value;
                this.OnTestWindowsChanged();
                this.OnPropertyChanged("TestWindows");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<global::ExampleODataFromDocumentDb.Client.Window> _TestWindows = new global::System.Collections.ObjectModel.ObservableCollection<global::ExampleODataFromDocumentDb.Client.Window>();
        partial void OnTestWindowsChanging(global::System.Collections.ObjectModel.ObservableCollection<global::ExampleODataFromDocumentDb.Client.Window> value);
        partial void OnTestWindowsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for HouseHistorySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("HouseHistorySingle")]
    public partial class HouseHistorySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<HouseHistory>
    {
        /// <summary>
        /// Initialize a new HouseHistorySingle object.
        /// </summary>
        public HouseHistorySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new HouseHistorySingle object.
        /// </summary>
        public HouseHistorySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new HouseHistorySingle object.
        /// </summary>
        public HouseHistorySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<HouseHistory> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for HouseHistory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.EntitySet("HouseHistory")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("HouseHistory")]
    public partial class HouseHistory : House
    {
        /// <summary>
        /// Create a new HouseHistory object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static HouseHistory CreateHouseHistory(string ID)
        {
            HouseHistory houseHistory = new HouseHistory();
            houseHistory.Id = ID;
            return houseHistory;
        }
        /// <summary>
        /// There are no comments for Property ModifiedId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedId")]
        public string ModifiedId
        {
            get
            {
                return this._ModifiedId;
            }
            set
            {
                this.OnModifiedIdChanging(value);
                this._ModifiedId = value;
                this.OnModifiedIdChanged();
                this.OnPropertyChanged("ModifiedId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ModifiedId;
        partial void OnModifiedIdChanging(string value);
        partial void OnModifiedIdChanged();
        /// <summary>
        /// There are no comments for Property ModifyAction in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifyAction")]
        public string ModifyAction
        {
            get
            {
                return this._ModifyAction;
            }
            set
            {
                this.OnModifyActionChanging(value);
                this._ModifyAction = value;
                this.OnModifyActionChanged();
                this.OnPropertyChanged("ModifyAction");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ModifyAction;
        partial void OnModifyActionChanging(string value);
        partial void OnModifyActionChanged();
        /// <summary>
        /// There are no comments for Property ModifyTimestamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifyTimestamp")]
        public global::System.Nullable<global::System.DateTimeOffset> ModifyTimestamp
        {
            get
            {
                return this._ModifyTimestamp;
            }
            set
            {
                this.OnModifyTimestampChanging(value);
                this._ModifyTimestamp = value;
                this.OnModifyTimestampChanged();
                this.OnPropertyChanged("ModifyTimestamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifyTimestamp;
        partial void OnModifyTimestampChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifyTimestampChanged();
    }
    /// <summary>
    /// There are no comments for Window in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Window")]
    public partial class Window : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Window object.
        /// </summary>
        /// <param name="widthInches">Initial value of WidthInches.</param>
        /// <param name="heightInches">Initial value of HeightInches.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Window CreateWindow(int widthInches, int heightInches)
        {
            Window window = new Window();
            window.WidthInches = widthInches;
            window.HeightInches = heightInches;
            return window;
        }
        /// <summary>
        /// There are no comments for Property WidthInches in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("WidthInches")]
        public int WidthInches
        {
            get
            {
                return this._WidthInches;
            }
            set
            {
                this.OnWidthInchesChanging(value);
                this._WidthInches = value;
                this.OnWidthInchesChanged();
                this.OnPropertyChanged("WidthInches");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _WidthInches;
        partial void OnWidthInchesChanging(int value);
        partial void OnWidthInchesChanged();
        /// <summary>
        /// There are no comments for Property HeightInches in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HeightInches")]
        public int HeightInches
        {
            get
            {
                return this._HeightInches;
            }
            set
            {
                this.OnHeightInchesChanging(value);
                this._HeightInches = value;
                this.OnHeightInchesChanged();
                this.OnPropertyChanged("HeightInches");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _HeightInches;
        partial void OnHeightInchesChanging(int value);
        partial void OnHeightInchesChanged();
        /// <summary>
        /// There are no comments for Property Panes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Panes")]
        public global::System.Collections.ObjectModel.ObservableCollection<global::ExampleODataFromDocumentDb.Client.GlassPane> Panes
        {
            get
            {
                return this._Panes;
            }
            set
            {
                this.OnPanesChanging(value);
                this._Panes = value;
                this.OnPanesChanged();
                this.OnPropertyChanged("Panes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<global::ExampleODataFromDocumentDb.Client.GlassPane> _Panes = new global::System.Collections.ObjectModel.ObservableCollection<global::ExampleODataFromDocumentDb.Client.GlassPane>();
        partial void OnPanesChanging(global::System.Collections.ObjectModel.ObservableCollection<global::ExampleODataFromDocumentDb.Client.GlassPane> value);
        partial void OnPanesChanged();
        /// <summary>
        /// There are no comments for Property InstalledDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("InstalledDate")]
        public global::System.Nullable<global::System.DateTimeOffset> InstalledDate
        {
            get
            {
                return this._InstalledDate;
            }
            set
            {
                this.OnInstalledDateChanging(value);
                this._InstalledDate = value;
                this.OnInstalledDateChanged();
                this.OnPropertyChanged("InstalledDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _InstalledDate;
        partial void OnInstalledDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnInstalledDateChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for GlassPane in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("GlassPane")]
    public partial class GlassPane : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new GlassPane object.
        /// </summary>
        /// <param name="widthInches">Initial value of WidthInches.</param>
        /// <param name="heightInches">Initial value of HeightInches.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static GlassPane CreateGlassPane(int widthInches, int heightInches)
        {
            GlassPane glassPane = new GlassPane();
            glassPane.WidthInches = widthInches;
            glassPane.HeightInches = heightInches;
            return glassPane;
        }
        /// <summary>
        /// There are no comments for Property WidthInches in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("WidthInches")]
        public int WidthInches
        {
            get
            {
                return this._WidthInches;
            }
            set
            {
                this.OnWidthInchesChanging(value);
                this._WidthInches = value;
                this.OnWidthInchesChanged();
                this.OnPropertyChanged("WidthInches");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _WidthInches;
        partial void OnWidthInchesChanging(int value);
        partial void OnWidthInchesChanged();
        /// <summary>
        /// There are no comments for Property HeightInches in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HeightInches")]
        public int HeightInches
        {
            get
            {
                return this._HeightInches;
            }
            set
            {
                this.OnHeightInchesChanging(value);
                this._HeightInches = value;
                this.OnHeightInchesChanged();
                this.OnPropertyChanged("HeightInches");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _HeightInches;
        partial void OnHeightInchesChanging(int value);
        partial void OnHeightInchesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DocumentType in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DocumentType")]
    public enum DocumentType
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Invalid")]
        Invalid = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("House")]
        House = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("HouseHistory")]
        HouseHistory = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Car")]
        Car = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("CarHistory")]
        CarHistory = 4
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ExampleODataFromDocumentDb.Client.House as global::ExampleODataFromDocumentDb.Client.HouseSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ExampleODataFromDocumentDb.Client.HouseSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ExampleODataFromDocumentDb.Client.House> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ExampleODataFromDocumentDb.Client.HouseSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ExampleODataFromDocumentDb.Client.House as global::ExampleODataFromDocumentDb.Client.HouseSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ExampleODataFromDocumentDb.Client.HouseSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ExampleODataFromDocumentDb.Client.House> source,
            string id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ExampleODataFromDocumentDb.Client.HouseSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ExampleODataFromDocumentDb.Client.HouseHistory as global::ExampleODataFromDocumentDb.Client.HouseHistorySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ExampleODataFromDocumentDb.Client.HouseHistorySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ExampleODataFromDocumentDb.Client.HouseHistory> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ExampleODataFromDocumentDb.Client.HouseHistorySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ExampleODataFromDocumentDb.Client.HouseHistory as global::ExampleODataFromDocumentDb.Client.HouseHistorySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ExampleODataFromDocumentDb.Client.HouseHistorySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ExampleODataFromDocumentDb.Client.HouseHistory> source,
            string id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ExampleODataFromDocumentDb.Client.HouseHistorySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Cast an entity of type global::ExampleODataFromDocumentDb.Client.House to its derived type global::ExampleODataFromDocumentDb.Client.HouseHistory
        /// </summary>
        /// <param name="source">source entity</param>
        public static global::ExampleODataFromDocumentDb.Client.HouseHistorySingle CastToHouseHistory(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::ExampleODataFromDocumentDb.Client.House> source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::ExampleODataFromDocumentDb.Client.HouseHistory> query = source.CastTo<global::ExampleODataFromDocumentDb.Client.HouseHistory>();
            return new global::ExampleODataFromDocumentDb.Client.HouseHistorySingle(source.Context, query.GetPath(null));
        }
    }
}
